// Property form constants — ported from client AddPropertyContent.jsx

export const PROPERTY_CATEGORIES = {
    Residential: {
        types: ["Apartment / Flat","Independent House","Villa","Builder Floor","Row House","Studio Apartment","Penthouse","Farm House"],
        desc: "Homes for living",
        amenities: ["Lift","Gym","Swimming Pool","Club House","Power Backup","CCTV","Parking Covered","Parking Open","Modular Kitchen","Wardrobes","Geyser","AC","Fans","Water Purifier","Intercom","Garden","Jogging Track","Kids Play Area","Community Hall","RO Water","Store Room","Servant Room"],
    },
    Commercial: {
        types: ["Office Space","Shop / Retail","Showroom","Restaurant / Cafe","Co-Working Space","Warehouse / Godown","Industrial Shed","Commercial Building / Floor"],
        desc: "Business spaces",
        amenities: ["Lift","Power Backup","CCTV","Fire Safety","Reserved Parking","Visitor Parking","Internet","Loading Dock","Goods Lift","Sprinkler System","Water Storage","Security","Washrooms","AC"],
    },
};

export const COMMERCIAL_CONFIGS = {
    "Office Space": { fields: ["workstations","conferenceRooms","cabins","washrooms","pantry"], label: "Office Configuration" },
    "Shop / Retail": { fields: ["frontage","washrooms","storage","displayWindows"], label: "Shop Configuration" },
    "Showroom": { fields: ["frontage","washrooms","storage","displayArea","parking"], label: "Showroom Configuration" },
    "Restaurant / Cafe": { fields: ["seatingCapacity","kitchenArea","washrooms","barArea","outdoorSeating"], label: "Restaurant Configuration" },
    "Co-Working Space": { fields: ["workstations","meetingRooms","privateCabins","phoneBooths","loungeArea"], label: "Co-Working Configuration" },
    "Warehouse / Godown": { fields: ["loadingDocks","ceilingHeight","floorLoadCapacity","officeSpace","washrooms"], label: "Warehouse Configuration" },
    "Industrial Shed": { fields: ["ceilingHeight","floorLoadCapacity","powerConnection","overheadCrane","officeSpace"], label: "Industrial Configuration" },
    "Commercial Building / Floor": { fields: ["washrooms","pantry","centralAC","powerBackup","parking"], label: "Building Configuration" },
};

export const IMAGE_CATEGORIES = {
    Residential: {
        "Apartment / Flat": [
            { key: "exterior", label: "Building Exterior", maxImages: 3 },
            { key: "livingRoom", label: "Living Room", maxImages: 4 },
            { key: "bedroom", label: "Bedroom(s)", maxImages: 4 },
            { key: "bathroom", label: "Bathroom(s)", maxImages: 3 },
            { key: "kitchen", label: "Kitchen", maxImages: 2 },
            { key: "balcony", label: "Balcony / Terrace", maxImages: 2 },
            { key: "parking", label: "Parking Area", maxImages: 2 },
            { key: "floorPlan", label: "Floor Plan", maxImages: 1 },
            { key: "other", label: "Other Areas", maxImages: 5 },
        ],
        "Independent House": [
            { key: "exterior", label: "House Exterior", maxImages: 4 },
            { key: "livingRoom", label: "Living Room", maxImages: 3 },
            { key: "bedroom", label: "Bedroom(s)", maxImages: 4 },
            { key: "bathroom", label: "Bathroom(s)", maxImages: 3 },
            { key: "kitchen", label: "Kitchen", maxImages: 2 },
            { key: "garden", label: "Garden/Lawn", maxImages: 3 },
            { key: "parking", label: "Parking", maxImages: 2 },
            { key: "floorPlan", label: "Floor Plan", maxImages: 1 },
            { key: "other", label: "Other", maxImages: 5 },
        ],
        "Villa": [
            { key: "exterior", label: "Villa Exterior", maxImages: 5 },
            { key: "livingRoom", label: "Living Room", maxImages: 4 },
            { key: "bedroom", label: "Bedroom(s)", maxImages: 5 },
            { key: "bathroom", label: "Bathroom(s)", maxImages: 3 },
            { key: "kitchen", label: "Kitchen", maxImages: 2 },
            { key: "garden", label: "Garden", maxImages: 3 },
            { key: "balcony", label: "Balcony / Terrace", maxImages: 3 },
            { key: "parking", label: "Parking", maxImages: 2 },
            { key: "floorPlan", label: "Floor Plan", maxImages: 1 },
            { key: "other", label: "Other", maxImages: 5 },
        ],
        "Builder Floor": [
            { key: "exterior", label: "Building Exterior", maxImages: 2 },
            { key: "livingRoom", label: "Living Room", maxImages: 3 },
            { key: "bedroom", label: "Bedrooms", maxImages: 4 },
            { key: "bathroom", label: "Bathroom(s)", maxImages: 3 },
            { key: "kitchen", label: "Kitchen", maxImages: 2 },
            { key: "balcony", label: "Balcony", maxImages: 2 },
            { key: "parking", label: "Parking", maxImages: 2 },
            { key: "floorPlan", label: "Floor Plan", maxImages: 1 },
            { key: "other", label: "Other", maxImages: 5 },
        ],
        "Studio Apartment": [
            { key: "livingRoom", label: "Studio Space", maxImages: 4 },
            { key: "kitchen", label: "Kitchen", maxImages: 2 },
            { key: "bathroom", label: "Bathroom", maxImages: 2 },
            { key: "balcony", label: "Balcony", maxImages: 2 },
            { key: "other", label: "Other", maxImages: 3 },
        ],
        "Penthouse": [
            { key: "exterior", label: "Building & Terrace", maxImages: 4 },
            { key: "livingRoom", label: "Living Area", maxImages: 4 },
            { key: "bedroom", label: "Bedroom(s)", maxImages: 4 },
            { key: "bathroom", label: "Bathroom(s)", maxImages: 3 },
            { key: "kitchen", label: "Kitchen", maxImages: 2 },
            { key: "balcony", label: "Balcony", maxImages: 2 },
            { key: "parking", label: "Parking", maxImages: 2 },
            { key: "floorPlan", label: "Floor Plan", maxImages: 1 },
            { key: "other", label: "Other", maxImages: 5 },
        ],
        "Row House": [
            { key: "exterior", label: "House Exterior", maxImages: 3 },
            { key: "livingRoom", label: "Living Room", maxImages: 3 },
            { key: "bedroom", label: "Bedrooms", maxImages: 4 },
            { key: "bathroom", label: "Bathroom(s)", maxImages: 3 },
            { key: "kitchen", label: "Kitchen", maxImages: 2 },
            { key: "garden", label: "Garden / Front Yard", maxImages: 3 },
            { key: "parking", label: "Parking", maxImages: 2 },
            { key: "floorPlan", label: "Floor Plan", maxImages: 1 },
            { key: "other", label: "Other", maxImages: 5 },
        ],
        "Farm House": [
            { key: "exterior", label: "Property Exterior", maxImages: 5 },
            { key: "livingRoom", label: "Living Space", maxImages: 3 },
            { key: "bedroom", label: "Bedrooms", maxImages: 4 },
            { key: "bathroom", label: "Bathroom(s)", maxImages: 3 },
            { key: "kitchen", label: "Kitchen", maxImages: 2 },
            { key: "garden", label: "Garden / Lawn", maxImages: 5 },
            { key: "parking", label: "Parking / Driveway", maxImages: 3 },
            { key: "floorPlan", label: "Floor / Site Plan", maxImages: 1 },
            { key: "other", label: "Other", maxImages: 5 },
        ],
    },
    Commercial: {
        "Office Space": [
            { key: "facade", label: "Building Exterior", maxImages: 4 },
            { key: "reception", label: "Reception / Lobby", maxImages: 3 },
            { key: "workArea", label: "Open Work Area", maxImages: 6 },
            { key: "cabin", label: "Cabins / Private Rooms", maxImages: 4 },
            { key: "conferenceRoom", label: "Conference / Meeting Rooms", maxImages: 3 },
            { key: "pantry", label: "Pantry / Cafeteria", maxImages: 3 },
            { key: "washroom", label: "Washrooms", maxImages: 3 },
            { key: "parking", label: "Parking Area", maxImages: 3 },
            { key: "floorPlan", label: "Floor Plan", maxImages: 1 },
            { key: "other", label: "Other Areas", maxImages: 5 },
        ],
        "Shop / Retail": [
            { key: "facade", label: "Shop Front / Facade", maxImages: 4 },
            { key: "shopFloor", label: "Shop Floor", maxImages: 6 },
            { key: "displayArea", label: "Display / Window Area", maxImages: 4 },
            { key: "storageArea", label: "Back Storage / Inventory", maxImages: 4 },
            { key: "washroom", label: "Washrooms", maxImages: 2 },
            { key: "parking", label: "Customer Parking", maxImages: 3 },
            { key: "floorPlan", label: "Floor Plan", maxImages: 1 },
            { key: "other", label: "Other Areas", maxImages: 5 },
        ],
        "Showroom": [
            { key: "facade", label: "Showroom Exterior", maxImages: 4 },
            { key: "reception", label: "Reception / Front Desk", maxImages: 3 },
            { key: "displayArea", label: "Display Area", maxImages: 6 },
            { key: "seatingArea", label: "Customer Seating / Lounge", maxImages: 3 },
            { key: "storageArea", label: "Back Office / Storage", maxImages: 3 },
            { key: "parking", label: "Parking", maxImages: 3 },
            { key: "floorPlan", label: "Floor Plan", maxImages: 1 },
            { key: "other", label: "Other Areas", maxImages: 5 },
        ],
        "Restaurant / Cafe": [
            { key: "facade", label: "Exterior / Entrance", maxImages: 4 },
            { key: "seatingArea", label: "Dining / Seating Area", maxImages: 6 },
            { key: "kitchenCommercial", label: "Commercial Kitchen", maxImages: 4 },
            { key: "washroom", label: "Washrooms", maxImages: 3 },
            { key: "storageArea", label: "Storage / Prep Area", maxImages: 3 },
            { key: "parking", label: "Parking / Valet Area", maxImages: 3 },
            { key: "floorPlan", label: "Floor Plan", maxImages: 1 },
            { key: "other", label: "Other Areas", maxImages: 5 },
        ],
        "Co-Working Space": [
            { key: "facade", label: "Exterior", maxImages: 3 },
            { key: "reception", label: "Reception / Entry", maxImages: 3 },
            { key: "workArea", label: "Open Desk Area", maxImages: 6 },
            { key: "cabin", label: "Private Cabins", maxImages: 4 },
            { key: "conferenceRoom", label: "Meeting / Conference Rooms", maxImages: 3 },
            { key: "seatingArea", label: "Lounge / Breakout", maxImages: 3 },
            { key: "pantry", label: "Pantry / Cafe", maxImages: 3 },
            { key: "other", label: "Other Areas", maxImages: 5 },
        ],
        "Warehouse / Godown": [
            { key: "facade", label: "Warehouse Exterior", maxImages: 3 },
            { key: "warehouse", label: "Main Storage Area", maxImages: 8 },
            { key: "loadingArea", label: "Loading / Unloading Area", maxImages: 4 },
            { key: "storageArea", label: "Racks / Internal Storage", maxImages: 4 },
            { key: "parking", label: "Truck / Vehicle Parking", maxImages: 3 },
            { key: "floorPlan", label: "Site / Floor Plan", maxImages: 1 },
            { key: "other", label: "Other Areas", maxImages: 5 },
        ],
        "Industrial Shed": [
            { key: "facade", label: "Shed Exterior", maxImages: 3 },
            { key: "warehouse", label: "Main Production Floor", maxImages: 8 },
            { key: "loadingArea", label: "Loading / Dock Area", maxImages: 4 },
            { key: "storageArea", label: "Storage / Raw Material", maxImages: 4 },
            { key: "parking", label: "Parking / Yard", maxImages: 3 },
            { key: "floorPlan", label: "Layout / Floor Plan", maxImages: 1 },
            { key: "other", label: "Other Areas", maxImages: 5 },
        ],
        "Commercial Building / Floor": [
            { key: "facade", label: "Building Exterior", maxImages: 4 },
            { key: "reception", label: "Main Lobby / Reception", maxImages: 3 },
            { key: "workArea", label: "Typical Floor / Work Area", maxImages: 6 },
            { key: "cabin", label: "Cabins / Offices", maxImages: 4 },
            { key: "conferenceRoom", label: "Conference Rooms", maxImages: 3 },
            { key: "parking", label: "Parking Levels", maxImages: 4 },
            { key: "floorPlan", label: "Floor Plan", maxImages: 2 },
            { key: "other", label: "Other Areas", maxImages: 5 },
        ],
    },
};

export const STEPS = [
    { id: 1, label: "Builder & Type" },
    { id: 2, label: "Location" },
    { id: 3, label: "Pricing & Area" },
    { id: 4, label: "Details" },
    { id: 5, label: "Photos" },
    { id: 6, label: "Review" },
];

export const INITIAL_FORM = {
    builderId: "",
    listingType: "Sale",
    propertyCategory: "Residential",
    propertyType: "Apartment / Flat",
    bhkType: "",
    bedrooms: "",
    bathrooms: 1,
    balconies: 0,
    builtUpArea: "",
    carpetArea: "",
    superBuiltUpArea: "",
    plotArea: "",
    expectedPrice: "",
    maintenanceIncluded: true,
    maintenance: "",
    expectedDeposit: "",
    bookingAmount: "",
    priceNegotiable: false,
    gstApplicable: false,
    furnishing: "Unfurnished",
    floorNo: "",
    totalFloors: "",
    propertyAge: "New",
    facing: "",
    constructionStatus: "Ready to Move",
    washrooms: 1,
    workstations: "",
    conferenceRooms: "",
    cabins: "",
    pantry: "",
    frontage: "",
    storage: "",
    seatingCapacity: "",
    kitchenArea: "",
    meetingRooms: "",
    privateCabins: "",
    loadingDocks: "",
    ceilingHeight: "",
    floorLoadCapacity: "",
    parkingCovered: 0,
    parkingOpen: 0,
    selectedAmenities: [],
    servantRoom: false,
    poojaRoom: false,
    studyRoom: false,
    storeRoom: false,
    reraId: "",
    occupancyCertificate: false,
    availableFrom: new Date().toISOString().split("T")[0],
    city: "",
    locality: "",
    landmark: "",
    address: "",
    latitude: "",
    longitude: "",
    description: "",
    videoUrl: "",
};
